### PR TITLE
Setup testing environment for user frontend

### PR DESCRIPTION
**Pull request by jysmys**
[Pt link](https://www.pivotaltracker.com/story/show/172918036)

- installed cypress
- installed Enzyme and Jest
- installed start-server-and-test

### CODE REVIEW

**Review by kermit-klein — CHANGES_REQUESTED** [review]
Add PT Card link pls

**Review by ViaMarcus — APPROVED** [review]

**Review by kermit-klein — CHANGES_REQUESTED** [review]
Check semaphore build commands again, we should use the same command lines as in we did for release tracker, you can also check editorial semaphore build

**Comment by jysmys** [comment]
> Check semaphore build commands again, we should use the same command lines as in we did for release tracker, you can also check editorial semaphore build

That doesnt work either.
image

**Comment by kermit-klein** [comment]
> > Check semaphore build commands again, we should use the same command lines as in we did for release tracker, you can also check editorial semaphore build
> 
> That doesnt work either.
> image

It is actually working, after adding a test file it will turn green

**Comment by jysmys** [comment]
> > > Check semaphore build commands again, we should use the same command lines as in we did for release tracker, you can also check editorial semaphore build
> > 
> > 
> > That doesnt work either.
> > image
> 
> It is actually working, after adding a test file it will turn green

Great, then we settle with that

**Review by oliverochman — APPROVED** [review]

**Pull request merged**
